/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CreateLazyImport = createFileRoute('/create')()
const IndexLazyImport = createFileRoute('/')()
const UuidIndexLazyImport = createFileRoute('/$uuid/')()
const UuidUpdateLazyImport = createFileRoute('/$uuid/update')()

// Create/Update Routes

const CreateLazyRoute = CreateLazyImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UuidIndexLazyRoute = UuidIndexLazyImport.update({
  path: '/$uuid/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$uuid/index.lazy').then((d) => d.Route))

const UuidUpdateLazyRoute = UuidUpdateLazyImport.update({
  path: '/$uuid/update',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$uuid/update.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/$uuid/update': {
      id: '/$uuid/update'
      path: '/$uuid/update'
      fullPath: '/$uuid/update'
      preLoaderRoute: typeof UuidUpdateLazyImport
      parentRoute: typeof rootRoute
    }
    '/$uuid/': {
      id: '/$uuid/'
      path: '/$uuid'
      fullPath: '/$uuid'
      preLoaderRoute: typeof UuidIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CreateLazyRoute,
  UuidUpdateLazyRoute,
  UuidIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/$uuid/update",
        "/$uuid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create": {
      "filePath": "create.lazy.tsx"
    },
    "/$uuid/update": {
      "filePath": "$uuid/update.lazy.tsx"
    },
    "/$uuid/": {
      "filePath": "$uuid/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
